# Generated by Django 3.2.5 on 2021-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210720_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='annual_income',
            field=models.FloatField(default=None),
        ),
    ]
