# Generated by Django 3.2.5 on 2021-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_basicdetails_annual_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='enter_the_amount_to_be_transferred_in_INR',
            field=models.FloatField(),
        ),
    ]
