# Generated by Django 3.2.5 on 2021-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_basicdetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='user_name',
            field=models.EmailField(default=None, max_length=150, verbose_name='...@medbank.com'),
        ),
    ]
