# Generated by Django 3.2.5 on 2021-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_basicdetails_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='user_name',
            field=models.EmailField(default=None, max_length=150, verbose_name='username...@medbank.com'),
        ),
    ]
